name: Assess code format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flake8_lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "E203,W503"
          path: "."